### ISSUE TITLE
Extending Where Can Capture To

### ISSUE THREAD

**Issue by noctuid** [dhruvasagar/vim-dotoo#10]
My most used capture template for org mode was the special one that allows you to capture to the heading that you are currently clocked in under. The template looks like this:

```
("c" "Currently Clocked in" entry (clock)
             "* %? (Entered on %U)")
```

Basically it will just add this to the bottom of whatever heading you're clocked into with the time (which can already be done). I find this to be a great way to clock into a certain task in one file and then record small chunks of an accomplished task to that file without having to leave whatever file I'm working in to navigate back.

Also, my todo capture template looks like this:

```
("t" "Todo" entry (file+headline "~/log.org" "General Tasks")
```

I find it easier to be able to capture to the "right" place the first time to eliminate the need to refile (or in the case of my todo template, make refiling easier since it would be confined to that document). I understand that vim-dotoo isn't attempting to be a full org-mode replacement, but I think especially being able to capture to wherever you're currently clocked in can save a lot of time.

Also, this brings up a question I had about how vim-dotoo handles clocks. Since the capture template currently records the time spent in it, does that mean that you can have multiple clocks running at once? Or is that just an exception? Is there a way to disable this behaviour? It makes sense maybe for a meeting, but usually my captures take only a few seconds and I think it would make sense to be able to disable the clock in the template, (especially if you were capturing to something you were already clocked into).

**Comment by dhruvasagar** [comment]
## Capture
Capture templates certainly need some more love, I have had to give that another look for a while, perhaps sooner now that I see someone else needing the same.

## Clocking
Let me try and explain how vim-dotoo works with clocks. There are 2 plugins that deal with clocks.
1. LogBook: This is responsible for parsing the log entries within the headlines of any dotoo file.
2. Clock: This is responsible to starting / ending clocks and tries to ensure that there is only 1 running clock at a given time. As long as we use the clocking mappings you'll be good. However with manual edits it is possible to have multiple tasks clocking at a given time, at the moment the parser doesn't do anything with such a situation. Also the parser (it's a bug) is unable to `start` a clock if it's running which would try to ensure the above because it leads to a sort of a race condition and tries to start and stop clocks on every parse.

**Comment by dhruvasagar** [comment]
Btw, you can disable clocking while capturing by setting 'let g:dotoo#capture#clock = 0'

**Comment by dhruvasagar** [comment]
I think this is a good idea. I will try to add this bit by bit soon. Thanks for the help!

**Comment by dhruvasagar** [comment]
@noctuid I have recently added initial support for this in #59. It allows you to specify a target for the capture template which can either be a filename or a headline target (similar convention as used when moving headlines `filename:headline`). Let me know what you think and if this can be improved further.
