### ISSUE TITLE
Open capture and agenda in current window or tab

### ISSUE THREAD

**Issue by demiceOP** [dhruvasagar/vim-dotoo#142]
When using the capture feature or agenda, the window opens as a split, but how can I make it so that it opens in the current buffer window or as a tab.  
Thank you

**Comment by dhruvasagar** [comment]
@demiceOP I just pushed a minor update, added a new configuration `g:dotoo#capture#cmd` to allow defining this behavior. You may set it to `edit`, `split`, `vert split` or `tabedit` to open in same buffer, split, vertical split or new tab. I would not recommend `edit` since it will override the contents of the currently open buffer, however the others should be good. Let me know if it works as you expected.
