### ISSUE TITLE
Setting 'agenda files' doesn't work

### ISSUE THREAD

**Issue by khoi2401** [dhruvasagar/vim-dotoo#16]
Hi!

I've just installed vim-dotoo, but have a small issue. I added

    let g:dotoo#agenda#files = ['~/notes/*.dotoo']

in my .vimrc but nothing appears in the agenda.

When I'm editing a file in ~/notes/, the content of that particular file (and only that file) does appear in the agenda.

Can someone help me?

**Comment by dhruvasagar** [comment]
Hi,

Are there dotoo files in the `~/notes` directory ?

Also, agenda view shows tasks that have either a deadline / are scheduled. So do you have tasks in the files within that directory that have them ?

**Comment by khoi2401** [comment]
Yes for both. I have two dotoo files with scheduled tasks in both.

**Comment by dhruvasagar** [comment]
@khoi2401 You should press `.` within the agenda view to make sure you're looking at today's agenda. Besides that it would be nice if I could have a look at your files. Also give me your vim version details.

**Comment by khoi2401** [comment]
Hi,

Thanks for your quick replies. Here are the contents of the files:

    ~/notes » tail -n +1 *.dotoo
    ==> personal.dotoo <==
    * Calls
    ** Someone (Mumble)
    SCHEDULED: [2015-08-22 Sat 14:00]
    ** Someone else (Skype)
    SCHEDULED: [2015-08-23 Sun 14:00]
    
    ==> phd.dotoo <==
    * Research
    ** TODO Characterise operators of the direct product

    * Meetings
    ** TODO Y3 forms
    SCHEDULED: [2015-08-21 Fri 14:00]

I use vim 7.4.778 (gvim package on Archlinux) and have

    let g:dotoo#agenda#files = ['/home/khoi/notes/*.dotoo']

in my .vimrc.

It's probably a stupid error of syntax, in which case I apologise.

Thanks again for your help!

**Comment by dhruvasagar** [comment]
This is strange I copied your files in notes and then set the `g:dotoo#agenda#files` like you mentioned and it works as expected. Kindly try restarting vim. Also double check the spellings in the setting `['/home/khoi/notes/*.dotoo']`, make sure the directory ~/notes has the right permissions to allow vim to read + write to it.

Also do you have `set hidden` enabled ?

The last point might very well be the problem, I suppose I should highlight that in the docs a bit more because it has been on several occasions given problems to users.

**Comment by khoi2401** [comment]
Thanks! It does work with set hidden.

Thank you so much for dotoo, and while I'm at it, for table-mode as well.

**Comment by dhruvasagar** [comment]
Hehe, you're welcome! Hopefully it is as useful to you as it is to me :). Feel free to open ticket for issues or suggestions.
