### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by edkolev** [dhruvasagar/vim-dotoo#3]
Thank you for this plugin!

Could you provide some docs about basic usage? This is what I consider a decent documentation on vim plugins:
1. example of a core functionality, preferably with a screenshot -- this is to get users interested
2. example of basic usage, to get users started with core features
3. details about all of the features of the plugin, to allow users to take full advantage of the plugin

From what I see, 1. and 3. are covered (although not in that order). This is a request for 2.

I've found this to be a good read on documentation in general http://stevelosh.com/blog/2013/09/teach-dont-tell/

Thanks again!

**Comment by rafi** [comment]
+1, for org-mode newcomers, stuff's little confusing :)

**Comment by dhruvasagar** [comment]
Sorry I haven't come to doing it yet, will try building one gradually.

**Comment by bbakersmith** [comment]
+1

**Comment by dhruvasagar** [comment]
Does the doc (readme) not suffice ?

**Comment by sgronblo** [comment]
I think the documentation should include some more example of the actual syntax. Currently there seems to be an assumption that everybody is familiar with the org-mode syntax.

**Comment by dhruvasagar** [comment]
Alright, I will add that.

**Comment by cstsunfu** [comment]
+10086

**Comment by dhruvasagar** [comment]
I am seriously considering if I should rewrite the parser in a better language like golang and interface with it.

At the very least there is certainly scope for refactoring the parser.

I will formulate more documentation regarding the file format as I do that.

**Comment by edkolev** [comment]
> I am seriously considering if I should rewrite the parser in a better language like golang and interface with it.

You'll probably shrink your user base -  installation will include more steps, plus not everyone would freely install a binary

**Comment by dhruvasagar** [comment]
Good point, although I value correctness, maintainability more than user base, I would still prefer to stay true to my original intent while I was building this in pure viml, which is to stay as pure as possible and avoid unnecessary depedencies.

I will still build a parser in golang, but that would be more for educational purposes, for my own good.

I will plan towards a major refactor and try to add much needed documentation for this. I want to take this plugin to a place where I can enable the community further into contributing, maintaining and improving this rather than me doing it alone when I can find time. Hopefully I can do it justice in an appropriate amount of time.

**Comment by hasufell** [comment]
The documentation jumps straight to key bindings. It doesn't even say how to use this plugin. How do you "open" it?

**Comment by dhruvasagar** [comment]
@hasufell I believe the README does a good job at explaining that, I can add it to vim doc too if it helps.

**Comment by dhruvasagar** [comment]
@hasufell Most of the workflows I use this for is via the agenda views, looking at the agenda for a day is usually where the most value is. The rest of the workflows are pretty much with regards to the custom keybindings to do those specific actions within the document itself.

**Comment by hasufell** [comment]
>  I believe the README does a good job at explaining that

Where?

**Comment by dhruvasagar** [comment]
@hasufell With the help of the explanations of what they keybindings are for...There are also supporting screenshots. I do reckon a screencast would help much further but there's a lot to cover, I haven't gotten around to building one, but i'll prioritize it more now since there's some traction, I was earlier not seeing many people use this so didn't feel there's enough demand.

**Comment by dhruvasagar** [comment]
@hasufell @edkolev I have finally recorded a screencast and added a link to it in the README, hopefully it should be able to do justice
