### ISSUE TITLE
Agenda crashes on open

### ISSUE THREAD

**Issue by ghost** [dhruvasagar/vim-dotoo#46]
Hi there,

I currently have my agenda files set correctly according to the documentation. However, when I open the agenda view, it crashes and closes Vim. When I don't specify a directory, it will ask me if I want to add my current file to the list, and even if I say yes, it says I have no scheduled tasks when there clearly are for that day.

I also have set hidden included in my .vimrc, since I read that it's an issue for others, but that hasn't made anything better.

Let me know if there's anything you want to look at.

**Comment by rypb** [comment]
Just an update - this was on macOS using iTerm2. I just tried it on my Debian machine with the same configuration and the agenda doesn't crash, it just doesn't detect the scheduled items.

**Comment by dhruvasagar** [comment]
Since dotoo is a pure vimscript implementation, any crashes would ideally be bugs in vimscript rather than me, there's also a small likelyhood that perhaps vim ended up using too many resources as a result of some leak that may have caused it to crash.

Would it be possible to view your dotoo files ?
