### ISSUE TITLE
default directory should be created or docs should mention it needs to be configured

### ISSUE THREAD

**Issue by wsdookadr** [dhruvasagar/vim-dotoo#5]
Hi,

After hitting gC and t and creating a todo, and trying to save it, I get this
![](http://i.imgur.com/XCJS5gN.png)

Dhruva suggested on IRC that configuring `g:dotoo#agenda#files` and  `g:dotoo#capture#refile`(and this actually solved the problem) but maybe the documentation should be more clear in relation to this, or, as an alternative, the default directory can be created by `vim-dotoo` on initialization.

**Comment by dhruvasagar** [comment]
I believe, this error should itself be good enough to indicate that the directory should be created. I have provided related information in the help text since. I would hope that is good enough, I would not like to create any directories from within the plugin so as to leave that choice to the plugin user.
