### ISSUE TITLE
Separate DEADLINE and SCHEDULED dates

### ISSUE THREAD

**Issue by Gavinok** [dhruvasagar/vim-dotoo#72]
Currently as far as I can tell DEADLINE and SCHEDULED dates are treated the same and only one is shown in the agenda view. It would be nice to be able to see both the DEADLINE and the SCHEDULED dates in the agenda with some indication of the type.

**Comment by Gavinok** [comment]
In addition it would be nice to allow for an event to have both a DEADLINE and a SCHEDULE date.

**Comment by dhruvasagar** [comment]
Thanks for opening this issue, I am aware of this limitation and do plan to improve upon this idea and have it be more compatible with the way Org Mode deals with them.

**Comment by dhruvasagar** [comment]
@Gavinok Hey, I have pushed a new version 0.12.0. In this update I have improved the agenda view logic for distinguishing between Scheduled headlines vs headlines with a deadline. I've kept the logic as close to emacs org-mode as possible. Kindly take a look and let me know what you think when you find time.

NOTE: I will address adding support for both schedule & deadline on a headline as a separate ticket since that is slightly more involved
