### ISSUE TITLE
recognize .org files automatically

### ISSUE THREAD

**Issue by tbm** [dhruvasagar/vim-dotoo#78]
It seems only `.dotoo` files are recognized automatically. What about add `.org`?

**Comment by Gavinok** [comment]
@tbm I believe this is meant to avoid people from expecting complete org compatibly. Personally I just add support for .org files in my vimrc. That said I would like to have it as a native feature.

**Comment by kristijanhusak** [comment]
I'm using this as a workaround:
```vim
autocmd BufNewFile,BufRead *.org setf dotoo
```

**Comment by dhruvasagar** [comment]
Like @Gavinok said, the reason I don't this is because we aren't 100% compatible with org mode syntax and some of the dotoo features may not work properly as a result. For this reason, I am not doing this yet. If you're only using vim-dotoo to manage these files & todos you may use @kristijanhusak work around and it should work for the most part, however, especially for existing org files, or files that you edit outside of vim from emacs, for instance, it's likely that things may break. Until we can achieve greater compatibility I don't see a reason to add support for this from dotoo. We can get back to this in future.
