### ISSUE TITLE
Compatability with Org Mode for Inactive/Active Dates

### ISSUE THREAD

**Issue by angelic-sedition** [dhruvasagar/vim-dotoo#8]
Emacs' org mode uses <date> for active dates (these show up in the agenda) and [] for inactive dates (don't show up in the agenda). Adding this behaviour would be especially nice for anyone wanting to migrate their previously existing org file to vim-dotoo (as well as for anyone who would use both org mode and vim-dotoo).

**Comment by dhruvasagar** [comment]
Right, as of now I actually support only inactive dates and treat them as inactive. When it comes to deadlines/schedules and such I don't really think there is any value for those inactive dates.

Can you please take an example that might convince me otherwise besides that org-mode supports it ?

**Comment by angelic-sedition** [comment]
So if I understand correctly every date is inactive unless it is a deadline or schedule? This at least seems to be the behaviour for me. I think that it makes more sense than how org mode does it (I've never wanted an active date that wasn't a "deadline" or "scheduled"), so I think it seems like a better idea to keep it that way. However, would you be willing to let vim-dotoo be more lenient with regards to what is considered a date so that a date could be surrounded by either type of brackets?

**Comment by dhruvasagar** [comment]
I am willing to do it if there's value in it, even though it adds more complexity.
Right now vim-dotoo's agenda lists tasks that have either a deadline or a schedule.

I guess emacs' org-mode also lists todos in agenda which have dates in the task title and other places if it's an active date !? I don't particularly like that idea because it makes things complicated and I am not too sure if there's a whole lot of value in doing it.

If a task is supposed to have a date, why not add a deadline ?

**Comment by angelic-sedition** [comment]
> If a task is supposed to have a date, why not add a deadline ?

I agree that it makes sense to just add a deadline. Emacs' org-mode will list any dates in angle brackets in the agenda and ignore any others (even if they come after "DEADLINE:"). I completely agree that this would be more complicated and make less sense.

My suggestion is no longer to change how vim-dotoo works to match emacs' org-mode with regard to what shows up in the agenda. I'm just suggesting that it just also recognize `<date>` as a valid date (and have exactly the same behaviour as `[date]` currently does).

For example, the following would show up in the agenda:
```
...some task...
DEADLINE: <2015-02-04 Wed>
```

The reasons for this are still mostly for compatability, but I think it would be much simpler to implement. It would mean that one didn't have to convert all angle bracketed dates to use an org file with vim-dotoo.

**Comment by dhruvasagar** [comment]
Yes that sounds very reasonably, i'll surely give that a go.

**Comment by dhruvasagar** [comment]
Ok, now I have a question. What about when we make a change to the task (say change todo state or something else) via the system, and it would update `<2015-02-04 Wed>` to `[2015-02-04 Wed]` ?
Would that be acceptable !? The reason I am asking is because adding support for `<...>` is very easy however to add the logic to remember what format it was initially and make sure it's serialized back to the same is slightly more tedious. Just thinking out loud here, let me know what you think.

**Comment by angelic-sedition** [comment]
If it would be too much trouble to remember the initial state, would you be willing to have it default to using angle brackets next to a "DEADLINE" or "SCHEDULED" and square brackets otherwise? Again, this would serve no purpose other than compatability, but I don't think that it would negatively impact the user (unless one really didn't like how angle brackets looked...). If you think this would be too much trouble for something with little use, then I think it would be okay to let users deal with vim-dotoo reformatting a date if they needed to.

**Comment by dhruvasagar** [comment]
well i'll work it out over the weekend, i prefer the format to not change, and I don't want there to be any defaults per say as long as we're using both formats, which we are.

**Comment by dhruvasagar** [comment]
Well that reminds me, we would need to establish a 'default' perhaps ? I need to think about the Capture templates too. Will check over the weekend.

**Comment by angelic-sedition** [comment]
I think it would make sense to default to square brackets for everything except deadline/scheduled which would default to angle brackets. If you want a consistent default, then I'd say just stick with square brackets.

**Comment by dhruvasagar** [comment]
I have added preliminary support for <> timestamps, the existing flow should remain the same.
Capture plugin will however default to using square brackets [], however you could manually change it <> if you so choose to. Dotoo will make sure it uses the specific <> or [] as per what was there originally during parsing the document. Additionally I have also updated the syntax definitions to allow for this.

**Comment by angelic-sedition** [comment]
Thanks! That's working great. If someone wanted to use <>, they could easily change the capture template. 

Are you going to make further changes or should I close this?

**Comment by dhruvasagar** [comment]
I left it open to see if there was anything wrong, but I think we can close this for now, open an issue if you find any although I don't think there should be.

I need to add tests, the main reason i've been holding on is because I have a major urge to build a testing system for viml myself :), but i'll get to it soon.

**Comment by angelic-sedition** [comment]
Awesome. Everything seems to be working for me.
