### ISSUE TITLE
CLOCK: DotooAdjustDate and <C-C><C-C> do not update a wrong duration

### ISSUE THREAD

**Issue by belugame** [dhruvasagar/vim-dotoo#81]
Continued from https://github.com/dhruvasagar/vim-dotoo/issues/74#issuecomment-657118403

I noticed that the resulting duration of a CLOCK line does not update when changing the start/end time with DotooAdjustDate. 

Lets say you had a CLOCK with a 5 minute period and add 10 minutes to it, it will still say it was only 5 minutes long. Also with \<C-C\>\<C-C\>  it does not update.

**Comment by dhruvasagar** [comment]
Thanks!

**Comment by dhruvasagar** [comment]
@belugame DotooAdjustDate only adjusts a date, it does not save the file and for that reason it's not able to correct the clock entries by itself. However, if you adjusted the dates, saved the file and then hit `\<C-C><C-C>` anywhere on the clock line outside of the individual dates, it should fix the duration. I believe this is alright, I wouldn't consider saving the file automatically because I think that should be left to the user.
